### ISSUE TITLE
Unable to process JSON

### ISSUE THREAD

**Issue by parasyte** [librato/statsd-librato-backend#68] opened 2017-03-08 00:08 UTC
Seeing this in logs with version 2.0.2:

```
7 Mar 15:45:18 - DEBUG: Sending Payload: {"time":1488930300,"tags":{"host":"auth9.us-west-1"},"measurements":[{"name":"auth-server.request.auth.started","value":79171,"tags":{"source":"auth9.us-west-1"},"source":"auth9.us-west-1"},{"name":"auth-server.request.auth.abort","value":56851,"tags":{"source":"auth9.us-west-1"},"source":"auth9.us-west-1"},{"name":"auth-server.request.auth.completed","value":79157,"tags":{"source":"auth9.us-west-1"},"source":"auth9.us-west-1"},{"name":"auth-server.request.more_than_1","value":1983,"tags":{"source":"auth9.us-west-1"},"source":"auth9.us-west-1"},{"name":"auth-server.debug_timing.soter.get-time","count":192677,"sum":0,"min":0.020981,"max":1352.562189,"tags":{"source":"auth9.us-west-1"},"source":"auth9.us-west-1"},{"name":"auth-server.debug_timing.soter.batchset-time","count":399,"sum":0,"min":2.07901,"max":256.52194,"tags":{"source":"auth9.us-west-1"},"source":"auth9.us-west-1"},{"name":"auth-server.debug_timing.request_1.authenticator.validate","count":1983,"sum":0,"min":1356.827974,"max":4656.633854,"tags":{"source":"auth9.us-west-1"},"source":"auth9.us-west-1"},{"name":"auth-server.debug_timing.soter.set-time","count":1,"sum":0,"min":5.872965,"max":5.872965,"tags":{"source":"auth9.us-west-1"},"source":"auth9.us-west-1"},{"name":"auth-server.debug_timing.request_1.pool.get","count":1,"sum":0,"min":1352.202892,"max":1352.202892,"tags":{"source":"auth9.us-west-1"},"source":"auth9.us-west-1"},{"name":"auth-server.debug_timing.request_1.authcache.get","count":1,"sum":0,"min":1352.558136,"max":1352.558136,"tags":{"source":"auth9.us-west-1"},"source":"auth9.us-west-1"},{"name":"auth-server.debug_timing.request_1.authenticator.fetch_with_fallback","count":1,"sum":0,"min":1352.654934,"max":1352.654934,"tags":{"source":"auth9.us-west-1"},"source":"auth9.us-west-1"}]}
7 Mar 15:45:18 - LOG_ERR: Failed to post to Librato: HTTP 400: {"code":400,"message":"Unable to process JSON"}
```

Rolled back to version 0.1.7 and it's working.

**Comment by bryanmikaelian** [comment] 2017-03-08 00:23
👋  Thanks for the report! It definitely looks like the issue is happening when a `source`  field is in the measurement along with the `tags` field.

**Comment by parasyte** [comment] 2017-03-08 00:37
:+1:

**Comment by bryanmikaelian** [comment] 2017-04-05 17:47
This has likely been fixed in https://github.com/librato/statsd-librato-backend/pull/70. Going to close this out. Please re-open if the issue is still happening.

**Closed by bryanmikaelian** 2017-04-05 17:47 UTC
Labels: 2.x.x+, bug
